### PR TITLE
gccdump: disable view when invalid compiler selected

### LINKED ISSUE #618: Support binary mode for ICC
E.g. https://godbolt.org/g/86nUhZ - fails with missing libraries:

```
/opt/compiler-explorer/gcc-6.3.0/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../x86_64-linux-gnu/bin/ld: cannot find -lm
Compiler exited with result code 1
```

### LINKED ISSUE #638: gccdump button should be disabled when selected compiler is not gcc
It should be clearer that this only works with gcc:
 * do not allow to open window when compiler is not gcc 
 * display a clear message when compiler is changed after.

(as it si done for CFG)

I'll push a PR to fix this !

### PR DESCRIPTION
**Pull request by dkm**
Try to disable view's UI when an invalid compiler (ie. non-GCC) is
selected after the view is opened.
Also changed the hover tip for gccdump to be more homogeneous with
other buttons.

fix #638 

I've decided to follow the «quick and not so clean» path, instead of trying to refactor the compiler type system (could be a good exercise, but ti would take weeks before I could come up with something...)

### CODE REVIEW

**Comment by RabsRincon** [comment]
Ey Marc, thanks for this!
Are you sure you fixed #618 and not another one? I can't see a fix for that one in your commits!

**Comment by dkm** [comment]
:) Fixed the messages, sorry !

**Comment by RabsRincon** [comment]
Sorry to leave you waiting! I'll recheck in a bit and let you know if something need a tweak. Thanks again for the contributions and keep them coming 😀

File: static/gccdump-view.js [hunk 1]
```diff
@@ -127,6 +127,20 @@ define(function (require) {
...
 
+    // Disable view's menu when invalid compiler has been
+    // selected after view is opened.
+    GccDump.prototype.onUiNotReady = function () {
+        this.filters.off('change');
+        this.selectize.off('change');
+
+        // disable drop down menu and buttons
+        this.selectize.disable();
+        this.domRoot.find('.dump-filters').find('.btn')
```
Comment (RabsRincon) [inline static/gccdump-view.js]: Isn't `this.domRoot.find('.dump-filters .btn').prop("disabled", true);` similar (And maybe it performs better?)

Comment (dkm) [reply static/gccdump-view.js]: You're right. I think I ended up with this after copy/pasting/modifying some code. Fixed here and 2 other occurrences. Thanks for the review !

**Comment by dkm** [comment]
There is still an issue, but maybe it's not worth blocking this PR: when using a sharing link that has tge gccdump view opened on an unsupported compiler (eg. clang), the view is disabled as expected, but there is no message in the text area (should be «no output, maybe you switched to a non-GCC compiler ?»).
I may have some time later today to fix this small issue. If not, I'll take care of it later.

**Comment by RabsRincon** [comment]
Oh no worries! We can wait forever, no deadlines, no pressure! Just keep us posted either here or on Slack of any news 😁

**Comment by dkm** [comment]
@RabsRincon should be ok now. Was caused by now useless workaround for container order creation.
No more known issue with this one !

File: static/gccdump-view.js [hunk 2]
```diff
@@ -232,16 +228,19 @@ define(function (require) {
...
             this.selectize.clear(true);
             this.state.selectedPass = '';
             this.updatePass(this.filters, this.selectize, false);
-            this.showGccDumpResults('<no output>');
-        }
-        // enable UI on first compilation
-        if (!this.uiIsReady) {
-            this.uiIsReady = true;
-            this.onUiReady();
+            this.showGccDumpResults('<no output, maybe you switched to a non-GCC compiler ?>');
```
Comment (RabsRincon) [inline static/gccdump-view.js]: Last review I promise. Could you please capitalize the first N? :)

Comment (dkm) [reply static/gccdump-view.js]: No prob ! Done !
