### PR TITLE
Fix nav-bar Share overlapping other dropdowns

### LINKED ISSUE #1011: Share/Other dropdowns overlap
Hello, I'm back! Super low priority, but there's a small problem with the Share and Other/Policies dropdown. Basically, if you click Share, then click Other, the Share menu overlaps the Other menu (same with Policies). It sometimes works fine in the other direction.

Since this seems like a fairly simple issue, so if a contributor could just point me in the right direction I'd love to take a crack at this!

### PR DESCRIPTION
**Pull request by Noviv**
Turns out `click.editable` isn't fired when another dropdown is clicked, meaning this callback is never called. When changed to `mouseup`, the callback is called and the Share menu is successfully closed.

Also, it looks like this could also be solved by specifiying the layout properly in `views/index.pug` (like the Other and Policies dropdowns are specified), but that seemed like a larger fix. Plus this got the job done :)

Fixes #1011

### CODE REVIEW

**Comment by Noviv** [comment]
This should fix #1011 but I wasn't sure how to reference it properly, apologies!

**Comment by RabsRincon** [comment]
Hi @Noviv thanks for the fix!

For the record, GitHub recognizes some keywords to close issues, you can read more at https://help.github.com/articles/closing-issues-using-keywords/. I've updated your pr text with one so you can see it in action.

Did you check that it does not have any unwanted effects? I'd expect this callback to be run more often than the previous one, for more elements.

**Comment by Noviv** [comment]
@RabsRincon I couldn't find any unexpected behaviour when I changed it to `mousedown`, and I'm not sure it'll be called any more than `click` seeing as `mousedown`/`mouseup`/`click` must be called together. It might be better to switch to `mousedown` as when the user clicks somewhere else the Share dropdown should disappear immediately, not when they release - your call!

I also pushed one more change: the Other and Policies popovers seem to toggle, whereas Share was hiding + re-rendering on each click, I just added a simple toggle to fix this :)

File: static/sharing.js [hunk 1]
```diff
@@ -124,7 +124,13 @@ function initShareButton(getLink, layout) {
         placement: 'bottom',
         trigger: 'manual'
     }).click(function () {
-        getLink.popover('show');
+        // load opposite state on click to prevent unnecessary popover rendering
```
Comment (RabsRincon) [inline static/sharing.js]: Shouldn't `.popover('toggle')` do the same, but with less boilerplate?

Comment (Noviv) [reply static/sharing.js]: Totally right, I should've done a little more research haha - commit coming right up!

**Comment by RabsRincon** [comment]
So, it works like a charm, which is great!

Thanks for the fix. It should hit the live site "soon". I'll be sure to let you know when it does :)
