### PR TITLE
Load modal on demand instead of on startup

### LINKED ISSUE #1514: [BUG] Completely unable to use save button
Pressing the button with the save icon does nothing.

Steps to reproduce the behaviour :
- Press the save icon on the top left

This does nothing, when it should open the save menu.

Godbolt after refreshing the page twice, refreshing while clearing the cache, restarting Firefox and finally attempting a system reboot (twice) and pressing the save icon ~50 times each : image

 - OS : Linux, Fedora 30 (64-bit) (core-4.1-amd64) (Linux kernel version 5.1.8-300 x86_64)
 - Browser : Firefox Nightly 67.0.2 (64-bit) for Fedora

Encountered this while trying to load some old code I was working with.

### PR DESCRIPTION
**Pull request by partouf**
Fixes #1514

The loadSave gets constructed really early, too early

### CODE REVIEW

File: static/loadSave.js [hunk 1]
```diff
@@ -42,25 +42,32 @@ function setLocalFile(name, file) {
...
-    this.modal.find('.save-button').click(_.bind(this.onSaveToBrowserStorage, this));
-    this.modal.find('.save-file').click(_.bind(this.onSaveToFile, this));
 
     this.base = window.httpRoot;
     if (!this.base.endsWith('/')) {
         this.base += '/';
     }
 
     this.fetchBuiltins();
+    this.initializeIfNeeded();
```
Comment (RabsRincon) [inline static/loadSave.js]: I think this is not needed here, and we can postpone the init until run is called on the editor

Comment (partouf) [reply static/loadSave.js]: correct, have changed it
